In [1]:
from probe_design import *
from probe_design_utils import *
from probe_design_qc import *

## Example 1: Multidomain dCas9 Epigenome Editor Custom Probes

In [2]:
fasta_reference = "references/hMOI_Effectors.fasta"

xlsx_sheet_to_fasta(
    xlsx_path="references/Extended_data_table_2.xlsx",
    sheet_name="2B_selected_effectors",
    id_col="header",
    seq_col="sequence",
    output_fasta=fasta_reference
)

nominated_sites  = "probe_nomination/hMOI_Effectors_probes.fasta"
nominated_probes  = "probe_nomination/hMOI_Effectors_lhs_rhs_probes.fasta"

nominate_probes(fasta_reference)
lhs_rhs_probe_binding_site_split(nominated_sites, nominated_probes)

Wrote 37 sequences to references/hMOI_Effectors.fasta
Annotations written to: /data_gilbert3/jswinderman/FD/Probe_analysis_review/CoMPoSE_custom_probe/probe_nomination/hMOI_Effectors_annotations.csv
Probes written to: /data_gilbert3/jswinderman/FD/Probe_analysis_review/CoMPoSE_custom_probe/probe_nomination/hMOI_Effectors_probes.fasta
Sequence N17 has 90 potential probe binding sites passing threshold.
Sequence N34 has 126 potential probe binding sites passing threshold.
Sequence N105 has 91 potential probe binding sites passing threshold.
Sequence N111 has 14 potential probe binding sites passing threshold.
Sequence N131 has 236 potential probe binding sites passing threshold.
Sequence N151 has 229 potential probe binding sites passing threshold.
Sequence N190 has 132 potential probe binding sites passing threshold.
Sequence N218 has 83 potential probe binding sites passing threshold.
Sequence N246 has 56 potential probe binding sites passing threshold.
Sequence N252 has 290 potential probe binding sites passing threshold.
Sequence N281 has 12 potential probe binding sites passing threshold.
Sequence N282 has 53 potential probe binding sites passing threshold.
Sequence N284 has 123 potential probe binding sites passing threshold.
Sequence N313 has 60 potential probe binding sites passing threshold.
Sequence C32 has 18 potential probe binding sites passing threshold.
Sequence C46 has 194 potential probe binding sites passing threshold.
Sequence C131 has 209 potential probe binding sites passing threshold.
Sequence C185 has 202 potential probe binding sites passing threshold.
Sequence C191 has 251 potential probe binding sites passing threshold.
Sequence C239 has 170 potential probe binding sites passing threshold.
Sequence C257 has 18 potential probe binding sites passing threshold.
Sequence C267 has 42 potential probe binding sites passing threshold.
Sequence C278 has 255 potential probe binding sites passing threshold.
Sequence C280 has 43 potential probe binding sites passing threshold.
Sequence C281 has 7 potential probe binding sites passing threshold.
Sequence C285 has 103 potential probe binding sites passing threshold.
Sequence C299 has 142 potential probe binding sites passing threshold.
Sequence C306 has 138 potential probe binding sites passing threshold.
Sequence C346 has 23 potential probe binding sites passing threshold.
Sequence RC433 has 16 potential probe binding sites passing threshold.
Sequence DNMT3A has 169 potential probe binding sites passing threshold.
Sequence dCas9 has 460 potential probe binding sites passing threshold.
Sequence mNeongreen has 89 potential probe binding sites passing threshold.
Sequence tagBFP has 128 potential probe binding sites passing threshold.
Sequence DNMT3L has 104 potential probe binding sites passing threshold.
Sequence KRAB has 17 potential probe binding sites passing threshold.
Sequence CRISPRoff_dCas9 has 703 potential probe binding sites passing threshold.
LHS and RHS probes written to: probe_nomination/hMOI_Effectors_lhs_rhs_probes.fasta

In [3]:
blast_results = "probe_nomination/hMOI_Effectors_blast.txt"

subprocess.run(
    ["scripts/custom_probe_blast.sh", nominated_probes, blast_results, "-t", "8"],
    check=True,      
    text=True,
)

Querying 10192 probe arms against hs.refseq.rna using 8 thread(s)...
Retained 49320 hits of length >= 20: probe_nomination/hMOI_Effectors_blast.txt

CompletedProcess(args=['scripts/custom_probe_blast.sh', 'probe_nomination/hMOI_Effectors_lhs_rhs_probes.fasta', 'probe_nomination/hMOI_Effectors_blast.txt', '-t', '8'], returncode=0)

In [4]:
probe_annotations_csv = 'probe_nomination/hMOI_Effectors_annotations.csv'
blast_probe_annotation = 'probe_nomination/hMOI_Effectors_blast_annotations.csv'

lhs_df, rhs_df = read_blast_results(blast_results)
process_lhs_rhs(lhs_df,rhs_df,probe_annotations_csv, blast_probe_annotation)

,id,target,description,start,end,lhs_gc_content,rhs_gc_content,lhs_max_homopolymer,rhs_max_homopolymer,lhs_entropy,...,lhs_sequence,rhs_sequence,lhs_off_target_length,lhs_mismatch,lhs_max_off_target_binding,lhs_off_target_gene,rhs_off_target_length,rhs_mismatch,rhs_max_off_target_binding,rhs_off_target_gene
0,N17_bin_29,N17,50-bp bin starting at position 29,29,78,44.0,56.0,3,3,0.983,...,ATCAACTCTTCGATAAAGGTCCCGT,CTTGGTCCAGAACTTCGTCGCCCAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N17_bin_31,N17,50-bp bin starting at position 31,31,80,48.0,52.0,3,3,0.979,...,CAACTCTTCGATAAAGGTCCCGTCT,TGGTCCAGAACTTCGTCGCCCATAT,NaN,NaN,NaN,NaN,20.0,2.0,18.0,PPP6R3
2,N17_bin_32,N17,50-bp bin starting at position 32,32,81,44.0,52.0,3,3,0.979,...,AACTCTTCGATAAAGGTCCCGTCTT,GGTCCAGAACTTCGTCGCCCATATA,NaN,NaN,NaN,NaN,20.0,2.0,18.0,PPP6R3
3,N17_bin_35,N17,50-bp bin starting at position 35,35,84,48.0,52.0,3,3,0.971,...,TCTTCGATAAAGGTCCCGTCTTGGT,CCAGAACTTCGTCGCCCATATAAGG,NaN,NaN,NaN,NaN,21.0,2.0,19.0,EZH2
4,N17_bin_43,N17,50-bp bin starting at position 43,43,92,52.0,44.0,3,3,0.998,...,AAAGGTCCCGTCTTGGTCCAGAACT,TCGTCGCCCATATAAGGGATGTTAT,20.0,2.0,18.0,SLC39A9,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5091,CRISPRoff_dCas9_bin_4017,CRISPRoff_dCas9,50-bp bin starting at position 4017,4017,4066,52.0,60.0,3,3,0.993,...,TAGAGGGCACCTTGTACTCGTCAGT,GATCACGGCCCACCCGACGCTATTA,20.0,2.0,18.0,ATAD2B,NaN,NaN,NaN,NaN
5092,CRISPRoff_dCas9_bin_4020,CRISPRoff_dCas9,50-bp bin starting at position 4020,4020,4069,52.0,64.0,3,3,0.993,...,AGGGCACCTTGTACTCGTCAGTGAT,CACGGCCCACCCGACGCTATTAGTC,24.0,3.0,21.0,EXT2,NaN,NaN,NaN,NaN
5093,CRISPRoff_dCas9_bin_4041,CRISPRoff_dCas9,50-bp bin starting at position 4041,4041,4090,60.0,56.0,3,3,0.961,...,TGATCACGGCCCACCCGACGCTATT,AGTCCCGATGGCCAGTCCGATAGAA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5094,CRISPRoff_dCas9_bin_4044,CRISPRoff_dCas9,50-bp bin starting at position 4044,4044,4093,60.0,56.0,3,3,0.961,...,TCACGGCCCACCCGACGCTATTAGT,CCCGATGGCCAGTCCGATAGAATAC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5095,CRISPRoff_dCas9_bin_4050,CRISPRoff_dCas9,50-bp bin starting at position 4050,4050,4099,60.0,48.0,3,2,0.936,...,CCCACCCGACGCTATTAGTCCCGAT,GGCCAGTCCGATAGAATACTTCTTG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
nominated_probes = 'probe_nomination/hMOI_Effectors_top_probes.csv'
nominate_top_probe_set(blast_probe_annotation, nominated_probes)

WARNING: Only 2 probe(s) nominated for target C257
WARNING: Only 2 probe(s) nominated for target C281
WARNING: Only 2 probe(s) nominated for target N111
WARNING: Only 2 probe(s) nominated for target N281

,id,target,description,start,end,lhs_gc_content,rhs_gc_content,lhs_max_homopolymer,rhs_max_homopolymer,lhs_entropy,...,rhs_sequence,lhs_off_target_length,lhs_mismatch,lhs_max_off_target_binding,lhs_off_target_gene,rhs_off_target_length,rhs_mismatch,rhs_max_off_target_binding,rhs_off_target_gene,priority_score
1871,C131_bin_602,C131,50-bp bin starting at position 602,602,651,60.0,60.0,3,2,0.961,...,CAGGATCAGGCTGTGCCTCCAGACT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.403846
1953,C131_bin_1234,C131,50-bp bin starting at position 1234,1234,1283,60.0,56.0,3,3,0.985,...,CCCAACTTAGCTATCTCGGTGGCAG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.711538
2001,C131_bin_1583,C131,50-bp bin starting at position 1583,1583,1632,56.0,56.0,4,2,0.979,...,TAATGCCGTACAGGTCAGCAGAGGC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.134615
2108,C185_bin_474,C185,50-bp bin starting at position 474,474,523,56.0,56.0,3,3,0.977,...,AGTGTTGCTCCGTGTGTCCCAGATC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.403846
2138,C185_bin_673,C185,50-bp bin starting at position 673,673,722,56.0,56.0,2,3,0.977,...,GAAAGCAGATGGCCTGACAGGTTGC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.884615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4103,mNeongreen_bin_427,mNeongreen,50-bp bin starting at position 427,427,476,56.0,56.0,2,3,0.989,...,GCTTGAAATGGGCTCATGCCGTCAG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.096154
4142,mNeongreen_bin_639,mNeongreen,50-bp bin starting at position 639,639,688,52.0,56.0,3,3,0.985,...,GGCGGGAAGACTCGCATTGTCTTCT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.396552
4150,tagBFP_bin_38,tagBFP,50-bp bin starting at position 38,38,87,60.0,56.0,2,2,0.955,...,GCTGCTCGACGTAGGTCTCGTTGTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.557692
4195,tagBFP_bin_276,tagBFP,50-bp bin starting at position 276,276,325,56.0,60.0,4,3,0.957,...,CTGCATCACAGGGCCGTTGGATGTG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.019231
4222,tagBFP_bin_434,tagBFP,50-bp bin starting at position 434,434,483,56.0,60.0,3,4,0.979,...,GCTTGAAGAAGTCGGGGATGCCCTG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.403846

In [6]:
R2N = "CGGAGATGTGTATAAGAGACAG"

construct_custom_probe_opool(
    nominated_probe_csv="probe_nomination/hMOI_Effectors_top_probes.csv",
    pool_name="hMOI_Effectors",
    lhs_r2_adaptor=R2N,
    n_barcodes=16,
)

## Example 2: Masking Regions, Missense Variant T-cell Activating ORFs

In [7]:
xlsx_sheet_to_fasta(
    xlsx_path="references/Extended_data_table_3.xlsx",
    sheet_name="4E_Missense_ORF_Sequences",
    id_col="id",
    seq_col="sequence",
    output_fasta="references/Missense_ORFs.fasta"
)

nominate_probes("references/Missense_ORFs.fasta")
nominated_sites  = "probe_nomination/Missense_ORFs_probes.fasta"
nominated_probes = "probe_nomination/Missense_ORFs_lhs_rhs_probes.fasta"

lhs_rhs_probe_binding_site_split(nominated_sites,nominated_probes)

blast_results = "probe_nomination/Missense_ORFs_blast.txt"

subprocess.run(
    ["scripts/custom_probe_blast.sh", nominated_probes, blast_results],
    check=True,      
    text=True,
)

probe_annotations_csv = 'probe_nomination/Missense_ORFs_annotations.csv'
blast_probe_annotation_output = 'probe_nomination/Missense_ORFs_blast_annotations.csv'

lhs_df, rhs_df = read_blast_results(blast_results)
process_lhs_rhs(lhs_df,rhs_df,probe_annotations_csv,blast_probe_annotation_output)

Wrote 13 sequences to references/Missense_ORFs.fasta
Annotations written to: /data_gilbert3/jswinderman/FD/Probe_analysis_review/CoMPoSE_custom_probe/probe_nomination/Missense_ORFs_annotations.csv
Probes written to: /data_gilbert3/jswinderman/FD/Probe_analysis_review/CoMPoSE_custom_probe/probe_nomination/Missense_ORFs_probes.fasta
Sequence BRAF has 351 potential probe binding sites passing threshold.
Sequence CARD11 has 612 potential probe binding sites passing threshold.
Sequence CARD11-PIK3R3 has 259 potential probe binding sites passing threshold.
Sequence FOXO1 has 247 potential probe binding sites passing threshold.
Sequence FYN has 216 potential probe binding sites passing threshold.
Sequence MYCN has 113 potential probe binding sites passing threshold.
Sequence CCND3 has 91 potential probe binding sites passing threshold.
Sequence ZIM3_KRAB has 39 potential probe binding sites passing threshold.
Sequence Cas9 has 776 potential probe binding sites passing threshold.
Sequence BBz_CAR has 141 potential probe binding sites passing threshold.
Sequence PuroR has 85 potential probe binding sites passing threshold.
Sequence EGFP has 119 potential probe binding sites passing threshold.
Sequence mCherry has 88 potential probe binding sites passing threshold.
LHS and RHS probes written to: probe_nomination/Missense_ORFs_lhs_rhs_probes.fasta
Querying 6274 probe arms against hs.refseq.rna using 64 thread(s)...
Retained 27942 hits of length >= 20: probe_nomination/Missense_ORFs_blast.txt

,id,target,description,start,end,lhs_gc_content,rhs_gc_content,lhs_max_homopolymer,rhs_max_homopolymer,lhs_entropy,...,lhs_sequence,rhs_sequence,lhs_off_target_length,lhs_mismatch,lhs_max_off_target_binding,lhs_off_target_gene,rhs_off_target_length,rhs_mismatch,rhs_max_off_target_binding,rhs_off_target_gene
0,BRAF_bin_7,BRAF,50-bp bin starting at position 7,7,56,64.0,60.0,3,4,0.966,...,CGGGAATGCTCCGTAGCCACCAGCT,TGAATAGGGGTCTTGGGTGAGGCGC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BRAF_bin_8,BRAF,50-bp bin starting at position 8,8,57,60.0,60.0,3,4,0.985,...,GGGAATGCTCCGTAGCCACCAGCTT,GAATAGGGGTCTTGGGTGAGGCGCA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BRAF_bin_12,BRAF,50-bp bin starting at position 12,12,61,52.0,72.0,2,4,0.989,...,ATGCTCCGTAGCCACCAGCTTGAAT,AGGGGTCTTGGGTGAGGCGCAGGCG,NaN,NaN,NaN,NaN,23.0,2.0,21.0,LOC124904018
3,BRAF_bin_18,BRAF,50-bp bin starting at position 18,18,67,56.0,68.0,4,3,0.989,...,CGTAGCCACCAGCTTGAATAGGGGT,CTTGGGTGAGGCGCAGGCGTACAGG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BRAF_bin_20,BRAF,50-bp bin starting at position 20,20,69,52.0,68.0,4,3,0.998,...,TAGCCACCAGCTTGAATAGGGGTCT,TGGGTGAGGCGCAGGCGTACAGGGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3132,mCherry_bin_617,mCherry,50-bp bin starting at position 617,617,666,64.0,52.0,3,2,0.966,...,AACTCGTGGCCGTTCACGGAGCCCT,CCATGTGCACCTTGAAGCGCATGAA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3133,mCherry_bin_621,mCherry,50-bp bin starting at position 621,621,670,68.0,56.0,3,2,0.937,...,CGTGGCCGTTCACGGAGCCCTCCAT,GTGCACCTTGAAGCGCATGAACTCC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3134,mCherry_bin_623,mCherry,50-bp bin starting at position 623,623,672,64.0,52.0,3,2,0.953,...,TGGCCGTTCACGGAGCCCTCCATGT,GCACCTTGAAGCGCATGAACTCCTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3135,mCherry_bin_629,mCherry,50-bp bin starting at position 629,629,678,60.0,44.0,3,2,0.955,...,TTCACGGAGCCCTCCATGTGCACCT,TGAAGCGCATGAACTCCTTGATGAT,21.0,1.0,20.0,ABCC3,20.0,1.0,19.0,CYP26B1
3136,mCherry_bin_630,mCherry,50-bp bin starting at position 630,630,679,60.0,48.0,3,2,0.955,...,TCACGGAGCCCTCCATGTGCACCTT,GAAGCGCATGAACTCCTTGATGATG,21.0,1.0,20.0,ABCC3,20.0,1.0,19.0,CYP26B1

In [8]:
gapfill_file = 'references/Extended_data_table_3.xlsx'  
filtered_blast_annotation = 'probe_nomination/Missense_ORF_Sequences_blast_annotations_filtered.csv'  
gapfill_sheet = '4G_Gapfill_Position_Lengths'

filter_probes_and_save(blast_probe_annotation_output, gapfill_file, filtered_blast_annotation, gapfill_sheet)

nominated_probes = 'probe_nomination/Missense_ORF_top_probes.csv'
nominate_top_probe_set(filtered_blast_annotation, nominated_probes)


R2N = "CGGAGATGTGTATAAGAGACAG"

construct_custom_probe_opool(
    nominated_probe_csv="probe_nomination/Missense_ORF_top_probes.csv",
    pool_name="Missense_ORF",
    lhs_r2_adaptor=R2N,
    n_barcodes=4,
)

Filtered probes have been saved to probe_nomination/Missense_ORF_Sequences_blast_annotations_filtered.csv
Rows that will be removed:
                id target                         description  start  end  \
121   BRAF_bin_825   BRAF  50-bp bin starting at position 825    825  874
122   BRAF_bin_827   BRAF  50-bp bin starting at position 827    827  876
123   BRAF_bin_828   BRAF  50-bp bin starting at position 828    828  877
124   BRAF_bin_829   BRAF  50-bp bin starting at position 829    829  878
125   BRAF_bin_839   BRAF  50-bp bin starting at position 839    839  888
...            ...    ...                                 ...    ...  ...
1806  CCND3_bin_39  CCND3   50-bp bin starting at position 39     39   88
1807  CCND3_bin_49  CCND3   50-bp bin starting at position 49     49   98
1808  CCND3_bin_53  CCND3   50-bp bin starting at position 53     53  102
1809  CCND3_bin_54  CCND3   50-bp bin starting at position 54     54  103
1810  CCND3_bin_58  CCND3   50-bp bin starting at position 58     58  107

      lhs_gc_content  rhs_gc_content  lhs_max_homopolymer  \
121             68.0            52.0                    2
122             64.0            48.0                    2
123             60.0            52.0                    2
124             60.0            56.0                    3
125             44.0            48.0                    3
...              ...             ...                  ...
1806            52.0            68.0                    3
1807            64.0            56.0                    3
1808            60.0            48.0                    2
1809            60.0            52.0                    2
1810            60.0            52.0                    2

      rhs_max_homopolymer  lhs_entropy  ...               lhs_sequence  \
121                     3        0.937  ...  GCGTCGGCGCGGTGACGTTCAGCAT
122                     3        0.953  ...  GTCGGCGCGGTGACGTTCAGCATCT
123                     3        0.961  ...  TCGGCGCGGTGACGTTCAGCATCTT
124                     3        0.961  ...  CGGCGCGGTGACGTTCAGCATCTTT
125                     3        0.983  ...  ACGTTCAGCATCTTTACAGCAACGT
...                   ...          ...  ...                        ...
1806                    3        0.953  ...  TTTGACTTGGGCCCTGTGAACTGCT
1807                    3        0.970  ...  GCCCTGTGAACTGCTACCGCGAGGT
1808                    3        0.979  ...  TGTGAACTGCTACCGCGAGGTGCCT
1809                    3        0.979  ...  GTGAACTGCTACCGCGAGGTGCCTT
1810                    3        0.979  ...  ACTGCTACCGCGAGGTGCCTTAGGT

                   rhs_sequence  lhs_off_target_length lhs_mismatch  \
121   CTTTACAGCAACGTCTCCGTGCCAT                    NaN          NaN
122   TTACAGCAACGTCTCCGTGCCATTT                    NaN          NaN
123   TACAGCAACGTCTCCGTGCCATTTC                    NaN          NaN
124   ACAGCAACGTCTCCGTGCCATTTCC                    NaN          NaN
125   CTCCGTGCCATTTCCCTTTATACAC                    NaN          NaN
...                         ...                    ...          ...
1806  ACCGCGAGGTGCCTTAGGTGCGGGA                    NaN          NaN
1807  GCCTTAGGTGCGGGAGATGAAGATG                    NaN          NaN
1808  TAGGTGCGGGAGATGAAGATGTTTG                    NaN          NaN
1809  AGGTGCGGGAGATGAAGATGTTTGG                    NaN          NaN
1810  GCGGGAGATGAAGATGTTTGGCTAG                    NaN          NaN

     lhs_max_off_target_binding  lhs_off_target_gene  rhs_off_target_length  \
121                         NaN                  NaN                   25.0
122                         NaN                  NaN                   25.0
123                         NaN                  NaN                   20.0
124                         NaN                  NaN                   20.0
125                         NaN                  NaN                   22.0
...                         ...                  ...                    ...
1806                        NaN                  NaN                    NaN
1807                        NaN                  NaN                   21.0
1808                        NaN                  NaN                    NaN
1809                        NaN                  NaN                    NaN
1810                        NaN                  NaN                    NaN

      rhs_mismatch rhs_max_off_target_binding  rhs_off_target_gene
121            2.0                       23.0                 RAF1
122            2.0                       23.0                 RAF1
123            1.0                       19.0                 RAF1
124            1.0                       19.0                 RAF1
125            2.0                       20.0                 RAF1
...            ...                        ...                  ...
1806           NaN                        NaN                  NaN
1807           2.0                       19.0           PITRM1-AS1
1808           NaN                        NaN                  NaN
1809           NaN                        NaN                  NaN
1810           NaN                        NaN                  NaN

[119 rows x 23 columns]
WARNING: Only 1 probe(s) nominated for target ZIM3_KRAB

## Probe plotting and inspection

In [9]:
fd_seq = pd.DataFrame([(rec.id, str(rec.seq).upper()) for rec in SeqIO.parse("references/hMOI_Effectors.fasta", "fasta")], columns=["header", "sequence"],)
fd_blast_scored = calculate_priority_score(pd.read_csv('probe_nomination/hMOI_Effectors_blast_annotations.csv'))
fd_top = pd.read_csv('probe_nomination/hMOI_Effectors_top_probes.csv')

target_id = "C32" 
fd_sequence     = fd_seq.loc[fd_seq["header"] == target_id, "sequence"].values[0]
fd_blast_target = fd_blast_scored[fd_blast_scored["target"] == target_id].copy()
fd_top_target   = fd_top[fd_top["target"] == target_id].copy()
Path("plots").mkdir(exist_ok=True)
fig = plot_metrics(fd_sequence, seq_id="C32", blast_df=fd_blast_target, top_df=fd_top_target, svg_path=f"plots/{target_id}_QC.svg")

Saved: plots/C32_QC.svg